# Generated by Django 5.2.8 on 2025-11-22 21:47

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_promotion_delete_activity_discountpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=store.models.product_image_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'model')},
        ),
    ]
