# Generated by Django 5.2.8 on 2025-12-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='images_max_idx',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
