# Generated by Django 5.2.8 on 2025-12-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_images_product_images_max_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images_max_idx',
            new_name='images_max_ord',
        ),
    ]
