# Generated by Django 5.2.8 on 2025-12-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_images_max_idx_product_images_max_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='equipments',
            field=models.JSONField(default=list, verbose_name='配置'),
        ),
    ]
